# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SherpaOnnx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'onnxruntime-objc', :path =>"LocalPods/OnnxRuntime-Rain"
  
  pod 'Moya', '15.0.0'
  pod 'SwiftyJSON'
#  pod 'Alamofire', '~> 5.2'
  pod 'SSZipArchive'
  # Pods for SherpaOnnx
#  pod 'OfflinePod', :git =>"https://gitee.com/cocoaRain/offline-pod.git"
#  pod 'OfflinePod', :git =>"/Users/rain/Desktop/LianxianPro/OfflinePod/OfflineLocalPod/offline-pod"
  
#  pod 'GoogleMLKit/Translate', '~> 3.1.0'
#  pod 'Firebase/Core'
#  pod 'GoogleMLKit', '5.0'

  target 'SherpaOnnxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SherpaOnnxUITests' do
    # Pods for testing
  end

end

